//
//  CharactersListPresenter.swift
//  RickAndMortyCharacters
//
//  Created by Eros Maurilio on 04/04/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CharactersListPresentationLogic
{
  func presentSomething(response: CharactersList.Something.Response)
}

class CharactersListPresenter: CharactersListPresentationLogic
{
  weak var viewController: CharactersListDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: CharactersList.Something.Response)
  {
    let viewModel = CharactersList.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
